---
env:
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - id: protoc-gen-rangerrpc
    binary: 'protoc-gen-rangerrpc_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    main: protoc-gen-rangerrpc/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
  - id: protoc-gen-rangerrpc-swagger
    binary: 'protoc-gen-rangerrpc-swagger_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    main: protoc-gen-rangerrpc-swagger/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
archives:
  - id: releases
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  use: github-native
