// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.5
// source: oneof.proto

package oneof

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneOfRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Options:
	//
	//	*OneOfRequest_Text
	//	*OneOfRequest_Number
	Options       isOneOfRequest_Options `protobuf_oneof:"options"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfRequest) Reset() {
	*x = OneOfRequest{}
	mi := &file_oneof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfRequest) ProtoMessage() {}

func (x *OneOfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfRequest.ProtoReflect.Descriptor instead.
func (*OneOfRequest) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{0}
}

func (x *OneOfRequest) GetOptions() isOneOfRequest_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *OneOfRequest) GetText() string {
	if x != nil {
		if x, ok := x.Options.(*OneOfRequest_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *OneOfRequest) GetNumber() int64 {
	if x != nil {
		if x, ok := x.Options.(*OneOfRequest_Number); ok {
			return x.Number
		}
	}
	return 0
}

type isOneOfRequest_Options interface {
	isOneOfRequest_Options()
}

type OneOfRequest_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type OneOfRequest_Number struct {
	Number int64 `protobuf:"varint,2,opt,name=number,proto3,oneof"`
}

func (*OneOfRequest_Text) isOneOfRequest_Options() {}

func (*OneOfRequest_Number) isOneOfRequest_Options() {}

type OneOfReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Options:
	//
	//	*OneOfReply_Text
	//	*OneOfReply_Number
	Options       isOneOfReply_Options `protobuf_oneof:"options"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOfReply) Reset() {
	*x = OneOfReply{}
	mi := &file_oneof_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOfReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfReply) ProtoMessage() {}

func (x *OneOfReply) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfReply.ProtoReflect.Descriptor instead.
func (*OneOfReply) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{1}
}

func (x *OneOfReply) GetOptions() isOneOfReply_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *OneOfReply) GetText() string {
	if x != nil {
		if x, ok := x.Options.(*OneOfReply_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *OneOfReply) GetNumber() int64 {
	if x != nil {
		if x, ok := x.Options.(*OneOfReply_Number); ok {
			return x.Number
		}
	}
	return 0
}

type isOneOfReply_Options interface {
	isOneOfReply_Options()
}

type OneOfReply_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type OneOfReply_Number struct {
	Number int64 `protobuf:"varint,2,opt,name=number,proto3,oneof"`
}

func (*OneOfReply_Text) isOneOfReply_Options() {}

func (*OneOfReply_Number) isOneOfReply_Options() {}

var File_oneof_proto protoreflect.FileDescriptor

const file_oneof_proto_rawDesc = "" +
	"\n" +
	"\voneof.proto\x12\x05oneof\"I\n" +
	"\fOneOfRequest\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06number\x18\x02 \x01(\x03H\x00R\x06numberB\t\n" +
	"\aoptions\"G\n" +
	"\n" +
	"OneOfReply\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06number\x18\x02 \x01(\x03H\x00R\x06numberB\t\n" +
	"\aoptions27\n" +
	"\x05OneOf\x12.\n" +
	"\x04Echo\x12\x13.oneof.OneOfRequest\x1a\x11.oneof.OneOfReplyB(Z&go.mondoo.com/ranger-rpc/example/oneofb\x06proto3"

var (
	file_oneof_proto_rawDescOnce sync.Once
	file_oneof_proto_rawDescData []byte
)

func file_oneof_proto_rawDescGZIP() []byte {
	file_oneof_proto_rawDescOnce.Do(func() {
		file_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oneof_proto_rawDesc), len(file_oneof_proto_rawDesc)))
	})
	return file_oneof_proto_rawDescData
}

var file_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oneof_proto_goTypes = []any{
	(*OneOfRequest)(nil), // 0: oneof.OneOfRequest
	(*OneOfReply)(nil),   // 1: oneof.OneOfReply
}
var file_oneof_proto_depIdxs = []int32{
	0, // 0: oneof.OneOf.Echo:input_type -> oneof.OneOfRequest
	1, // 1: oneof.OneOf.Echo:output_type -> oneof.OneOfReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oneof_proto_init() }
func file_oneof_proto_init() {
	if File_oneof_proto != nil {
		return
	}
	file_oneof_proto_msgTypes[0].OneofWrappers = []any{
		(*OneOfRequest_Text)(nil),
		(*OneOfRequest_Number)(nil),
	}
	file_oneof_proto_msgTypes[1].OneofWrappers = []any{
		(*OneOfReply_Text)(nil),
		(*OneOfReply_Number)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oneof_proto_rawDesc), len(file_oneof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oneof_proto_goTypes,
		DependencyIndexes: file_oneof_proto_depIdxs,
		MessageInfos:      file_oneof_proto_msgTypes,
	}.Build()
	File_oneof_proto = out.File
	file_oneof_proto_goTypes = nil
	file_oneof_proto_depIdxs = nil
}
