// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.5
// source: optional.proto

package optional

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomType) Reset() {
	*x = CustomType{}
	mi := &file_optional_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomType) ProtoMessage() {}

func (x *CustomType) ProtoReflect() protoreflect.Message {
	mi := &file_optional_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomType.ProtoReflect.Descriptor instead.
func (*CustomType) Descriptor() ([]byte, []int) {
	return file_optional_proto_rawDescGZIP(), []int{0}
}

type OptionalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *string                `protobuf:"bytes,1,opt,name=text,proto3,oneof" json:"text,omitempty"`
	Number        *uint32                `protobuf:"varint,2,opt,name=number,proto3,oneof" json:"number,omitempty"`
	Flag          *bool                  `protobuf:"varint,3,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	Custom        *CustomType            `protobuf:"bytes,4,opt,name=custom,proto3,oneof" json:"custom,omitempty"` // tests that optional + custom type is a no-op
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalRequest) Reset() {
	*x = OptionalRequest{}
	mi := &file_optional_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalRequest) ProtoMessage() {}

func (x *OptionalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optional_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalRequest.ProtoReflect.Descriptor instead.
func (*OptionalRequest) Descriptor() ([]byte, []int) {
	return file_optional_proto_rawDescGZIP(), []int{1}
}

func (x *OptionalRequest) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *OptionalRequest) GetNumber() uint32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

func (x *OptionalRequest) GetFlag() bool {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return false
}

func (x *OptionalRequest) GetCustom() *CustomType {
	if x != nil {
		return x.Custom
	}
	return nil
}

type OptionalReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *string                `protobuf:"bytes,1,opt,name=text,proto3,oneof" json:"text,omitempty"`
	Number        *uint32                `protobuf:"varint,2,opt,name=number,proto3,oneof" json:"number,omitempty"`
	Flag          *bool                  `protobuf:"varint,3,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	Custom        *CustomType            `protobuf:"bytes,4,opt,name=custom,proto3,oneof" json:"custom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalReply) Reset() {
	*x = OptionalReply{}
	mi := &file_optional_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalReply) ProtoMessage() {}

func (x *OptionalReply) ProtoReflect() protoreflect.Message {
	mi := &file_optional_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalReply.ProtoReflect.Descriptor instead.
func (*OptionalReply) Descriptor() ([]byte, []int) {
	return file_optional_proto_rawDescGZIP(), []int{2}
}

func (x *OptionalReply) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *OptionalReply) GetNumber() uint32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

func (x *OptionalReply) GetFlag() bool {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return false
}

func (x *OptionalReply) GetCustom() *CustomType {
	if x != nil {
		return x.Custom
	}
	return nil
}

type OptionalRequest_InnerCustomType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        *bool                  `protobuf:"varint,1,opt,name=active,proto3,oneof" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalRequest_InnerCustomType) Reset() {
	*x = OptionalRequest_InnerCustomType{}
	mi := &file_optional_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalRequest_InnerCustomType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalRequest_InnerCustomType) ProtoMessage() {}

func (x *OptionalRequest_InnerCustomType) ProtoReflect() protoreflect.Message {
	mi := &file_optional_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalRequest_InnerCustomType.ProtoReflect.Descriptor instead.
func (*OptionalRequest_InnerCustomType) Descriptor() ([]byte, []int) {
	return file_optional_proto_rawDescGZIP(), []int{1, 0}
}

func (x *OptionalRequest_InnerCustomType) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

var File_optional_proto protoreflect.FileDescriptor

const file_optional_proto_rawDesc = "" +
	"\n" +
	"\x0eoptional.proto\x12\boptional\"\f\n" +
	"\n" +
	"CustomType\"\xf6\x01\n" +
	"\x0fOptionalRequest\x12\x17\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x88\x01\x01\x12\x1b\n" +
	"\x06number\x18\x02 \x01(\rH\x01R\x06number\x88\x01\x01\x12\x17\n" +
	"\x04flag\x18\x03 \x01(\bH\x02R\x04flag\x88\x01\x01\x121\n" +
	"\x06custom\x18\x04 \x01(\v2\x14.optional.CustomTypeH\x03R\x06custom\x88\x01\x01\x1a9\n" +
	"\x0fInnerCustomType\x12\x1b\n" +
	"\x06active\x18\x01 \x01(\bH\x00R\x06active\x88\x01\x01B\t\n" +
	"\a_activeB\a\n" +
	"\x05_textB\t\n" +
	"\a_numberB\a\n" +
	"\x05_flagB\t\n" +
	"\a_custom\"\xb9\x01\n" +
	"\rOptionalReply\x12\x17\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x88\x01\x01\x12\x1b\n" +
	"\x06number\x18\x02 \x01(\rH\x01R\x06number\x88\x01\x01\x12\x17\n" +
	"\x04flag\x18\x03 \x01(\bH\x02R\x04flag\x88\x01\x01\x121\n" +
	"\x06custom\x18\x04 \x01(\v2\x14.optional.CustomTypeH\x03R\x06custom\x88\x01\x01B\a\n" +
	"\x05_textB\t\n" +
	"\a_numberB\a\n" +
	"\x05_flagB\t\n" +
	"\a_custom2N\n" +
	"\x0fOptionalService\x12;\n" +
	"\x05Check\x12\x19.optional.OptionalRequest\x1a\x17.optional.OptionalReplyB+Z)go.mondoo.com/ranger-rpc/example/optionalb\x06proto3"

var (
	file_optional_proto_rawDescOnce sync.Once
	file_optional_proto_rawDescData []byte
)

func file_optional_proto_rawDescGZIP() []byte {
	file_optional_proto_rawDescOnce.Do(func() {
		file_optional_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optional_proto_rawDesc), len(file_optional_proto_rawDesc)))
	})
	return file_optional_proto_rawDescData
}

var file_optional_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_optional_proto_goTypes = []any{
	(*CustomType)(nil),                      // 0: optional.CustomType
	(*OptionalRequest)(nil),                 // 1: optional.OptionalRequest
	(*OptionalReply)(nil),                   // 2: optional.OptionalReply
	(*OptionalRequest_InnerCustomType)(nil), // 3: optional.OptionalRequest.InnerCustomType
}
var file_optional_proto_depIdxs = []int32{
	0, // 0: optional.OptionalRequest.custom:type_name -> optional.CustomType
	0, // 1: optional.OptionalReply.custom:type_name -> optional.CustomType
	1, // 2: optional.OptionalService.Check:input_type -> optional.OptionalRequest
	2, // 3: optional.OptionalService.Check:output_type -> optional.OptionalReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_optional_proto_init() }
func file_optional_proto_init() {
	if File_optional_proto != nil {
		return
	}
	file_optional_proto_msgTypes[1].OneofWrappers = []any{}
	file_optional_proto_msgTypes[2].OneofWrappers = []any{}
	file_optional_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optional_proto_rawDesc), len(file_optional_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optional_proto_goTypes,
		DependencyIndexes: file_optional_proto_depIdxs,
		MessageInfos:      file_optional_proto_msgTypes,
	}.Build()
	File_optional_proto = out.File
	file_optional_proto_goTypes = nil
	file_optional_proto_depIdxs = nil
}
