// Code generated by protoc-gen-rangerrpc version DO NOT EDIT.
// source: optional.proto

package optional

import (
	"context"
	"errors"
	"net/http"
	"net/url"
	"strings"

	ranger "go.mondoo.com/ranger-rpc"
	"go.mondoo.com/ranger-rpc/metadata"
	jsonpb "google.golang.org/protobuf/encoding/protojson"
	pb "google.golang.org/protobuf/proto"
)

// service interface definition

type OptionalService interface {
	Check(context.Context, *OptionalRequest) (*OptionalReply, error)
}

// client implementation

type OptionalServiceClient struct {
	ranger.Client
	httpclient ranger.HTTPClient
	prefix     string
}

func NewOptionalServiceClient(addr string, client ranger.HTTPClient, plugins ...ranger.ClientPlugin) (*OptionalServiceClient, error) {
	base, err := url.Parse(ranger.SanitizeUrl(addr))
	if err != nil {
		return nil, err
	}

	u, err := url.Parse("./OptionalService")
	if err != nil {
		return nil, err
	}

	serviceClient := &OptionalServiceClient{
		httpclient: client,
		prefix:     base.ResolveReference(u).String(),
	}
	serviceClient.AddPlugins(plugins...)
	return serviceClient, nil
}
func (c *OptionalServiceClient) Check(ctx context.Context, in *OptionalRequest) (*OptionalReply, error) {
	out := new(OptionalReply)
	err := c.DoClientRequest(ctx, c.httpclient, strings.Join([]string{c.prefix, "/Check"}, ""), in, out)
	return out, err
}

// server implementation

type OptionalServiceServerOption func(s *OptionalServiceServer)

func WithUnknownFieldsForOptionalServiceServer() OptionalServiceServerOption {
	return func(s *OptionalServiceServer) {
		s.allowUnknownFields = true
	}
}

func NewOptionalServiceServer(handler OptionalService, opts ...OptionalServiceServerOption) http.Handler {
	srv := &OptionalServiceServer{
		handler: handler,
	}

	for i := range opts {
		opts[i](srv)
	}

	service := ranger.Service{
		Name: "OptionalService",
		Methods: map[string]ranger.Method{
			"Check": srv.Check,
		},
	}
	return ranger.NewRPCServer(&service)
}

type OptionalServiceServer struct {
	handler            OptionalService
	allowUnknownFields bool
}

func (p *OptionalServiceServer) Check(ctx context.Context, reqBytes *[]byte) (pb.Message, error) {
	var req OptionalRequest
	var err error

	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, errors.New("could not access header")
	}

	switch md.First("Content-Type") {
	case "application/protobuf", "application/octet-stream", "application/grpc+proto":
		err = pb.Unmarshal(*reqBytes, &req)
	default:
		// handle case of empty object
		if len(*reqBytes) > 0 {
			err = jsonpb.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(*reqBytes, &req)
		}
	}

	if err != nil {
		return nil, err
	}
	return p.handler.Check(ctx, &req)
}
