// Copyright (c) Mondoo, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.5
// source: swagger-example.proto

package swagger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest_Corpus int32

const (
	ListRequest_UNIVERSAL ListRequest_Corpus = 0
	ListRequest_WEB       ListRequest_Corpus = 1
	ListRequest_IMAGES    ListRequest_Corpus = 2
	ListRequest_LOCAL     ListRequest_Corpus = 3
	ListRequest_NEWS      ListRequest_Corpus = 4
	ListRequest_PRODUCTS  ListRequest_Corpus = 5
	ListRequest_VIDEO     ListRequest_Corpus = 6
)

// Enum value maps for ListRequest_Corpus.
var (
	ListRequest_Corpus_name = map[int32]string{
		0: "UNIVERSAL",
		1: "WEB",
		2: "IMAGES",
		3: "LOCAL",
		4: "NEWS",
		5: "PRODUCTS",
		6: "VIDEO",
	}
	ListRequest_Corpus_value = map[string]int32{
		"UNIVERSAL": 0,
		"WEB":       1,
		"IMAGES":    2,
		"LOCAL":     3,
		"NEWS":      4,
		"PRODUCTS":  5,
		"VIDEO":     6,
	}
)

func (x ListRequest_Corpus) Enum() *ListRequest_Corpus {
	p := new(ListRequest_Corpus)
	*p = x
	return p
}

func (x ListRequest_Corpus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListRequest_Corpus) Descriptor() protoreflect.EnumDescriptor {
	return file_swagger_example_proto_enumTypes[0].Descriptor()
}

func (ListRequest_Corpus) Type() protoreflect.EnumType {
	return &file_swagger_example_proto_enumTypes[0]
}

func (x ListRequest_Corpus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListRequest_Corpus.Descriptor instead.
func (ListRequest_Corpus) EnumDescriptor() ([]byte, []int) {
	return file_swagger_example_proto_rawDescGZIP(), []int{6, 0}
}

// This is a status request
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_swagger_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_swagger_example_proto_rawDescGZIP(), []int{0}
}

type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// number of items included in the store
	Items int64 `protobuf:"varint,1,opt,name=items,proto3" json:"items,omitempty"`
	// number of used items
	Used int64 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	// list of request failures
	Failures      int64 `protobuf:"varint,3,opt,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_swagger_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_swagger_example_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetItems() int64 {
	if x != nil {
		return x.Items
	}
	return 0
}

func (x *StatsResponse) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *StatsResponse) GetFailures() int64 {
	if x != nil {
		return x.Failures
	}
	return 0
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	UserID        int32                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_swagger_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_swagger_example_proto_rawDescGZIP(), []int{2}
}

func (x *AddRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *AddRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    bool                   `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_swagger_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_swagger_example_proto_rawDescGZIP(), []int{3}
}

func (x *AddResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetURL     string                 `protobuf:"bytes,1,opt,name=targetURL,proto3" json:"targetURL,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_swagger_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_swagger_example_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetTargetURL() string {
	if x != nil {
		return x.TargetURL
	}
	return ""
}

func (x *DeleteRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    bool                   `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_swagger_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_swagger_example_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage int32                  `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	Corpus        ListRequest_Corpus     `protobuf:"varint,4,opt,name=corpus,proto3,enum=swagger.ListRequest_Corpus" json:"corpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_swagger_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_swagger_example_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListRequest) GetResultPerPage() int32 {
	if x != nil {
		return x.ResultPerPage
	}
	return 0
}

func (x *ListRequest) GetCorpus() ListRequest_Corpus {
	if x != nil {
		return x.Corpus
	}
	return ListRequest_UNIVERSAL
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Result              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Users         map[string]*User       `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_swagger_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_swagger_example_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListResponse) GetUsers() map[string]*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets      []string               `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_swagger_example_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_example_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_swagger_example_proto_rawDescGZIP(), []int{8}
}

func (x *Result) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Result) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Result) GetSnippets() []string {
	if x != nil {
		return x.Snippets
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int32                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_swagger_example_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_example_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_swagger_example_proto_rawDescGZIP(), []int{9}
}

func (x *User) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_swagger_example_proto protoreflect.FileDescriptor

const file_swagger_example_proto_rawDesc = "" +
	"\n" +
	"\x15swagger-example.proto\x12\aswagger\"4\n" +
	"\fStatsRequestJ\x04\b\x02\x10\x03J\x04\b\x0f\x10\x10J\x04\b\t\x10\fJ\b\b(\x10\x80\x80\x80\x80\x02R\x03FOOR\x03BAR\"U\n" +
	"\rStatsResponse\x12\x14\n" +
	"\x05items\x18\x01 \x01(\x03R\x05items\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x03R\x04used\x12\x1a\n" +
	"\bfailures\x18\x03 \x01(\x03R\bfailures\">\n" +
	"\n" +
	"AddRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x05R\x06userID\"-\n" +
	"\vAddResponse\x12\x1e\n" +
	"\n" +
	"successful\x18\x01 \x01(\bR\n" +
	"successful\"G\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\ttargetURL\x18\x01 \x01(\tR\ttargetURL\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"0\n" +
	"\x0eDeleteResponse\x12\x1e\n" +
	"\n" +
	"successful\x18\x01 \x01(\bR\n" +
	"successful\"\xfd\x01\n" +
	"\vListRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12&\n" +
	"\x0fresult_per_page\x18\x03 \x01(\x05R\rresultPerPage\x123\n" +
	"\x06corpus\x18\x04 \x01(\x0e2\x1b.swagger.ListRequest.CorpusR\x06corpus\"Z\n" +
	"\x06Corpus\x12\r\n" +
	"\tUNIVERSAL\x10\x00\x12\a\n" +
	"\x03WEB\x10\x01\x12\n" +
	"\n" +
	"\x06IMAGES\x10\x02\x12\t\n" +
	"\x05LOCAL\x10\x03\x12\b\n" +
	"\x04NEWS\x10\x04\x12\f\n" +
	"\bPRODUCTS\x10\x05\x12\t\n" +
	"\x05VIDEO\x10\x06\"\xba\x01\n" +
	"\fListResponse\x12)\n" +
	"\aresults\x18\x01 \x03(\v2\x0f.swagger.ResultR\aresults\x126\n" +
	"\x05users\x18\x02 \x03(\v2 .swagger.ListResponse.UsersEntryR\x05users\x1aG\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.swagger.UserR\x05value:\x028\x01\"L\n" +
	"\x06Result\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsnippets\x18\x03 \x03(\tR\bsnippets\",\n" +
	"\x04User\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x05R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xef\x01\n" +
	"\x0eExampleService\x120\n" +
	"\x03Add\x12\x13.swagger.AddRequest\x1a\x14.swagger.AddResponse\x129\n" +
	"\x06Delete\x12\x16.swagger.DeleteRequest\x1a\x17.swagger.DeleteResponse\x123\n" +
	"\x04List\x12\x14.swagger.ListRequest\x1a\x15.swagger.ListResponse\x12;\n" +
	"\n" +
	"Statistics\x12\x15.swagger.StatsRequest\x1a\x16.swagger.StatsResponseB*Z(go.mondoo.com/ranger-rpc/example/swaggerb\x06proto3"

var (
	file_swagger_example_proto_rawDescOnce sync.Once
	file_swagger_example_proto_rawDescData []byte
)

func file_swagger_example_proto_rawDescGZIP() []byte {
	file_swagger_example_proto_rawDescOnce.Do(func() {
		file_swagger_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swagger_example_proto_rawDesc), len(file_swagger_example_proto_rawDesc)))
	})
	return file_swagger_example_proto_rawDescData
}

var file_swagger_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_swagger_example_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_swagger_example_proto_goTypes = []any{
	(ListRequest_Corpus)(0), // 0: swagger.ListRequest.Corpus
	(*StatsRequest)(nil),    // 1: swagger.StatsRequest
	(*StatsResponse)(nil),   // 2: swagger.StatsResponse
	(*AddRequest)(nil),      // 3: swagger.AddRequest
	(*AddResponse)(nil),     // 4: swagger.AddResponse
	(*DeleteRequest)(nil),   // 5: swagger.DeleteRequest
	(*DeleteResponse)(nil),  // 6: swagger.DeleteResponse
	(*ListRequest)(nil),     // 7: swagger.ListRequest
	(*ListResponse)(nil),    // 8: swagger.ListResponse
	(*Result)(nil),          // 9: swagger.Result
	(*User)(nil),            // 10: swagger.User
	nil,                     // 11: swagger.ListResponse.UsersEntry
}
var file_swagger_example_proto_depIdxs = []int32{
	0,  // 0: swagger.ListRequest.corpus:type_name -> swagger.ListRequest.Corpus
	9,  // 1: swagger.ListResponse.results:type_name -> swagger.Result
	11, // 2: swagger.ListResponse.users:type_name -> swagger.ListResponse.UsersEntry
	10, // 3: swagger.ListResponse.UsersEntry.value:type_name -> swagger.User
	3,  // 4: swagger.ExampleService.Add:input_type -> swagger.AddRequest
	5,  // 5: swagger.ExampleService.Delete:input_type -> swagger.DeleteRequest
	7,  // 6: swagger.ExampleService.List:input_type -> swagger.ListRequest
	1,  // 7: swagger.ExampleService.Statistics:input_type -> swagger.StatsRequest
	4,  // 8: swagger.ExampleService.Add:output_type -> swagger.AddResponse
	6,  // 9: swagger.ExampleService.Delete:output_type -> swagger.DeleteResponse
	8,  // 10: swagger.ExampleService.List:output_type -> swagger.ListResponse
	2,  // 11: swagger.ExampleService.Statistics:output_type -> swagger.StatsResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_swagger_example_proto_init() }
func file_swagger_example_proto_init() {
	if File_swagger_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swagger_example_proto_rawDesc), len(file_swagger_example_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swagger_example_proto_goTypes,
		DependencyIndexes: file_swagger_example_proto_depIdxs,
		EnumInfos:         file_swagger_example_proto_enumTypes,
		MessageInfos:      file_swagger_example_proto_msgTypes,
	}.Build()
	File_swagger_example_proto = out.File
	file_swagger_example_proto_goTypes = nil
	file_swagger_example_proto_depIdxs = nil
}
